apiVersion: apps/v1
kind: Deployment
metadata:
  name: springpet
spec:
  selector:
    matchLabels:
      app: springpet
  template:
    metadata:
      labels:
        app: springpet
    spec:
      containers:
      - name: springpet
        image: '322676149291.dkr.ecr.us-east-1.amazonaws.com/springpetclinic:latest'
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080